### ISSUE TITLE
There is a relative reasearch

### ISSUE THREAD

**Issue by SCUTykLin** [allanj/Deductive-MWP#2]
《A Bottom-Up DAG Structure Extraction Model for Math Word Problems》AAAI 2021，framework and perspective are the same as you. They do not have Rationalizer and the other part of the model is the same as u.

U did't read that? But I saw u refer a relative paper in AAAI 2021<Hms: A hierarchical solver with dependency-enhanced understanding for math word problem.>

**Comment by SCUTykLin** [comment]
The new perspective is the greatest contribution of your paper, but now there is an paper that is older than you

**Comment by allanj** [comment]
Thanks a lot for your interest. In fact, we cited this paper in the related work. 
We would like to point out some differences.

The Seq2DAG approach is pretty nice in the sense that it can solve both "Arithmetic word problems" and "Algebra word problems" using the way to solve the algebra problem, by introducing variables "x", "y", etc. In the following discussion, we focus on the methodology for arithmetic word problems, which is the scope we consider.


1. As shown in Figure 1 and Algorithm 1 of Seq2DAG, Seq2DAG considers all the possible equations at each layer. For example, Let's say (a+b)*(c+d), in the first layer, this approach considers both "a+b" and "c+d" at the same time and classifies them to be "positive".  While in our approach, we still perform sequentially for these two expressions.  Actually, we also try such a previous approach in our experiments (although there is no codebase for that), the performance is actually quite suboptimal (Table 3 Seq2DAG without BERT 72.5 compared with Graph2Tree 75.5). Our guess is that such a method probably pushes a lot of burden on the model to simultaneously predict many expressions/equations at the beginning. Also, the expressions in the first step do not aware of each other while making predictions
2. Prior knowledge constraint: I believe the constraint used in our paper can be applied to Seq2DAG as well but would be a different story for applying that.

It's good to have this discussion, feel free to comment if you have a different opinion on this.

**Comment by SCUTykLin** [comment]
The different point 1: In this paper, your model just add the top-k expressions to candidate, right? But I think it's a small difference.

And another question, in seq2DAG，they argue that the model should follow some mathematical law, such as communicate law. And I know that you use $FFN_{op}([q_i, q_j, q_i*q_j])$，all operation do not satisfy communicate law. Have you tried to separate addition, multiplication and subtraction, division? addition and multiplication satisfy communicate, $FFN_{op}([q_i + q_j, q_j + q_i, q_i*q_j])$; subtraction and division are $FFN_{op}([q_i, q_j, q_i*q_j])$?

I try in seq2Tree(GTS)，Ineffective

**Comment by SCUTykLin** [comment]
GTS：74.7%
GTS-communicate: 73.5%-75.2%，unstable. I've been tuning parameters for a long time.
And seq2DAG is similar to u, maybe u are effective.

**Comment by allanj** [comment]
> The different point 1: In this paper, your model just add the top-k expressions to candidate, right? But I think it's a small difference.
> 
> And another question, in seq2DAG，they argue that the model should follow some mathematical law, such as communicate law. And I know that you use $FFN_{op}([q_i, q_j, q_i_q_j])$，all operation do not satisfy communicate law. Have you tried to separate addition, multiplication and subtraction, division? addition and multiplication satisfy communicate, $FFN_{op}([q_i + q_j, q_j + q_i, q_i_q_j])$; subtraction and division are $FFN_{op}([q_i, q_j, q_i*q_j])$?
> 
> I try in seq2Tree(GTS)，Ineffective

Sorry, I'm a bit confused about this part, what do you mean by "top-k expressions here"? Or maybe top-1? In our dataset, we preprocess the dataset to have step-by-step equations. 

In my very early experiments, I tried something `q_i + q_j`, the results do not change so much though (in my early-stage experiments.) But the communicate law is definitely something that I didn't put too much effort on. I simply use a reverse relation for subtraction and division to complement that effect.  But the underlying method here might not be the optimal one.

**Comment by allanj** [comment]
> Have you tried to separate addition, multiplication and subtraction, division? addition and multiplication satisfy communicate, $FFN_{op}([q_i + q_j, q_j + q_i, q_iq_j])$; subtraction and division are $FFN_{op}([q_i, q_j, q_i*q_j])$?


This will be another way to try. I didn't think of this but just use opposite relation.

**Comment by SCUTykLin** [comment]
OK, I try that in your code. Thanks for your reply. Actually I am just curious for the effectiveness of the  communicate law. seq2DAG do not provide the code and you give me a Chance.

**Comment by allanj** [comment]
Sure. Do not hesitate to let me know if you need some help.

**Comment by allanj** [comment]
FYI, not sure it may help or not, https://github.com/allanj/Deductive-MWP/blob/parallel_labels/src/model/parallel_model.py in other branches implemented something similar to Seq2DAG, but I didn't get really good performance.

**Comment by SCUTykLin** [comment]
Thank u very much.I will see that.

**Comment by SCUTykLin** [comment]
emm, another question for the Math23k dataset. Where is the valid data of Math23k?

**Comment by allanj** [comment]
Oops, sorry, I forgot to upload that. Thanks for the reminder. Just uploaded
One more thing to note is that:
1. the original dataset released by Tencent does not split a validation set.
2. But following works split a validation set.

Although many works there are not comparable, we try to make everything comparable there.

**Comment by SCUTykLin** [comment]
Did u use beam search? I read the paper and said you did not use beam search.

**Comment by allanj** [comment]
No, I didn't use beam search. Using beam search could be harmful to the model prediction as well

**Comment by SCUTykLin** [comment]
emmmm，section 4.3，Our current model performs the greedy search in tring and inference process, which could be improved with beam search process.

**Comment by allanj** [comment]
To clarify, it would be harmful if we directly use the vanilla beam search algorithm in implementation because of the theoretical challenges.

In theory, using beam search should be helpful as in we are able to see more candidates. But we have to overcome the theoretical challenge which is the unbalanced probability distribution. Thus, we might need to propose/design a better beam search algorithm for doing beam search.

**Comment by allanj** [comment]
You can also refer to Section 4.3 for the theoretical challenge.
<img width="375" alt="image" src="https://user-images.githubusercontent.com/3351187/165447889-0ee8f3ae-d355-4a94-9af7-1627e2312b52.png">
