### ISSUE TITLE
Cannot run your training code

### ISSUE THREAD

**Issue by qfkkwgd** [allanj/Deductive-MWP#3]
Hi,

Thanks for your work.

I just downloaded your latest code and tried to reproduce your results. However, I encountered a bug saying
"universal_main.py: error: unrecognized arguments: --add_new_token=0 --diff_param_for_height=0 --filtered_steps -1". 

Even after I manually removed these three parameters, there are still bugs saying
"FileNotFoundError: [Errno 2] No such file or directory: 'data/mawps-single/mawps_train_nodup.json'".

Do you know how to fix the issue?

Thanks!

**Comment by allanj** [comment]
Sure. For the MAWPS dataset, we only conduct the 5-fold cross-validation experiments in the paper. Thus, I didn't upload the train/test splits for MAWPS.

So maybe you can run the script with five folds. https://github.com/allanj/Deductive-MWP/blob/main/scripts/run_mawps_five_fold.bash

**Comment by ProxJ** [comment]
Hi @allanj,
I noticed that `run_math23k_five_fold.bash` tries to get data from `data/math23k_five_fold/` which is missing as well, but the the paper reports on this. Is it possible to upload the split?

**Comment by allanj** [comment]
Sure. Here comes the five-fold data: https://drive.google.com/file/d/1oQZUPeIA6TlNySqjcZhTMQA4-onwljTU/view?usp=sharing. I didn't upload it to GitHub as it is a bit large for GitHub.
