### ISSUE TITLE
A question about dataset evaluation. 

### ISSUE THREAD

**Issue by hyx1999** [allanj/Deductive-MWP#6]
5-fold cross validation is used on the MAWPS dataset. For each of the five experiments, should I choose the best result in the validation set or use other results？

**Comment by allanj** [comment]
For 5-fold cross validation, there is no actual external validation set.

We split the dataset in the 5 folds, use 4 fold for training and the res for evaluation. Then we take the best performance on the current validation set.

**Comment by hyx1999** [comment]
Thank you for your answer!
